2022-12-10 09:59:21,441 ERROR: Exception on /index [POST] [in /Users/dyue/venvs/microblog/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/Users/dyue/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dyue/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dyue/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dyue/venvs/microblog/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/dyue/venvs/microblog/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/dyue/Dropbox/Projects/WebDevelopment/microblog/app/routes.py", line 21, in index
    post = Post(body=form.post.data, author=current_user)
NameError: name 'Post' is not defined
2022-12-10 10:00:38,595 INFO: Microblog startup [in /Users/dyue/Dropbox/Projects/WebDevelopment/microblog/app/__init__.py:44]
2022-12-10 12:28:24,874 INFO: Microblog startup [in /Users/dyue/Dropbox/Projects/WebDevelopment/microblog/app/__init__.py:46]
